config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users do
    resources :documents
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  validates :title, :amount, :down_payment, :interest_rate, presence: true
  validates :title, length: { maximum: 20 }
  validates :amount, :down_payment, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :interest_rate, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 50 }

  has_attached_file :doc_pdf
  validates_attachment_content_type :doc_pdf, content_type: "application/pdf"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :documents
  # validates :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
  end

  def create
    @user = current_user
    @document = @user.documents.new(doc_params) 
    @document.save
    pdf = DocPdf.new(@document)
    pdf.render_file("#{Rails.root}/public/#{@document.id}.pdf")  
    @document.doc_pdf_file_name = pdf.file_name
    # binding.pry
    if @document.save
      s3 = Aws::S3::Resource.new(
       credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY']),
       region: ENV['AWS_S3_REGION'])

      s3.bucket(ENV['S3_BUCKET']).object(pdf.file_name).upload_file("#{Rails.root}/public/#{@document.id}.pdf")
      File.delete("#{Rails.root}/public/#{@document.id}.pdf")

      DocMailer.doc_confirmation(@user, @document).deliver_now
      redirect_to user_path(@user, @document), notice: 'Document was successfully created. Email confirmation sent'
    else
      redirect_to root_path, alert: "Document did not save. Please resubmit"

    end
  end

  # def show
  #   @document = Document.find(params[:id])

  #   respond_to do |format|
  #     format.html 
  #     format.pdf do 
  #       pdf = DocPdf.new(@document)

  #       send_data pdf.render, type: 'application/pdf', disposition: "inline"
  #     end
  #   end
  # end

  private

  def doc_params
    params.require(:document).permit(:title, :amount, :interest_rate, :down_payment, :doc_pdf)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
   if user_signed_in?

    redirect_to user_path(current_user)
   end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @documents = @user.documents.order("created_at DESC")
    
   unless @user == current_user
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Document</h4>
      </div>
      <div class="modal-body">
        <%= render 'documents/new' %>
      </div>     
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div> 

app/views/documents/_new.html.erb
<%= form_for :document, url: user_documents_path(@user) do |f| %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :title, :class => "control-label" %>
        <%= f.select :title, ["Home mortgage", "Auto loan", "School loan", "Personal loan"], { include_blank: true }, :class => "form-control" %></br>
        <%= f.label :amount, :class => "control-label" %>
        <%= f.text_field :amount, :class => "form-control" %></br>
        <%= f.label :down_payment, :class => "control-label" %>
        <%= f.text_field :down_payment, :class => "form-control" %></br>
        <%= f.label :interest_rate, :class => "control-label" %>
        <%= f.text_field :interest_rate, :class => "form-control" %></br>
        <%= f.submit class: "btn btn-primary"%>
      </div>
    </div> 
<% end %>
 

app/views/home/index.html.erb
<div class="jumbotron">
  <h2 class="white left_margin">Welcome to DocGenerator</h2>
</div>
<div id="project_description">
  <h3>About this project</h3>
  <p>DocGenerator is designed to generate a PDF document for its users. Users can securely login in and access their documents at any time. DocGenerator was built as a Rails 4 project and utilizes Devise for authentication, Prawn for PDF generation and Paperclip to upload PDF documents to Amazon S3. Source code can be found here    <a href="https://github.com/lea3182/Doc_Generator"><i class="fa fa-github fa-lg"></i></a></p>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> nbm">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-static-top">
  <div class="navbar-brand">DocGenerator</div>
    <div class="container">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse navHeaderCollapse">
        <ul class="nav navbar-nav navbar-right">
         <% if current_user %>
           <li><%=link_to 'Edit account', edit_user_registration_path %></li>
           <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
         <% else %>
           <li class="active"><%=link_to "Home", root_path %></li>
           <li><%=link_to "Login", new_user_session_path %></li>
           <li><%=link_to "SignUp", new_user_registration_path %></li>
         <% end %>
       </ul>    
     </div>   <!-- collapse -->
  </div>   <!-- container div -->
</div>    <!-- navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DocGenerator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/messages' %>
  <%= yield %>
</body>
</html>

app/views/users/show.html.erb
<div class="container">
  <h1 class="page-header"><%= @user.first_name %>'s Dashboard</h1>
  <%=link_to 'Create a Document', new_user_document_path(@user), { :class => ' btn btn-success btn pull-right create-link', 'data-toggle' => 'modal', 'data-target' => '#myModal'} %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><h4>Date</h4></th>
          <th><h4>Loan Title</h4></th>
          <th><h4>Loan Amount</h4></th>
          <th><h4>Down Payment</h4></th>
          <th><h4>Interest Rate</h4></th>
          <th><h4>View PDF</h4></th>
        </tr>
      </thead>
      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <td><%= document.created_at.strftime("%m-%d-%Y") %></td>
            <td><%= document.title %></td>
            <td><%= number_to_currency(document.amount, precision: 0)%></td>
            <td><%= number_to_currency(document.down_payment, precision: 0) %></td>
            <td><%= number_to_percentage(document.interest_rate, precision: 2) %></td>
            <td ><%= link_to '<i class="fa fa-file-pdf-o fa-2x"></i>'.html_safe, document.doc_pdf.url %></td> 
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>           <!-- table-responsive -->
  <%= render "documents/modal" %>
</div>          <!-- container --> 